apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  namespace: poc-itt
spec:
  type: LoadBalancer
  selector:
    app: user-management-app
  ports:
  - port: 3000
    targetPort: 3000