
name: container deployment

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Deployment environment'
        options:
          - prod
          - test
          - all
        required: true
      version:
        description: 'application version'
        required: true

env:
  ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID  }}
  ARM_CLIENT_ID: ${{  secrets.ARM_CLIENT_ID  }}

jobs:
  
  deploy_on_azure_container_service:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: configure client secret
      run: export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
    
    - name: configure subscription id
      run: export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
    
    - name: configure tenant id
      run: export ARM_TENANT_ID=$ARM_TENANT_ID

    - name: configure client id
      run: export ARM_CLIENT_ID=$ARM_CLIENT_ID

    - name: Initialize Terraform
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform init

    - name: Try terraform plan on ALL
      if: ${{ github.event.inputs.env == 'all' }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform plan -var application_version=${{ github.event.inputs.version }}

    - name: Deployment on ALL env
      if: ${{ github.event.inputs.env  == 'all' }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform apply -var application_version=${{ github.event.inputs.version }} -auto-approve

    - name: Try terraform plan on PROD env
      if: ${{ github.event.inputs.env  == 'prod' }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform plan -var application_version=${{ github.event.inputs.version }} -target azurerm_container_group.container-poc-${{ github.event.inputs.env }}

    - name: Deployment on PROD env
      if: ${{ github.event.inputs.env == 'prod' }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform apply -var application_version=${{ github.event.inputs.version }} -target azurerm_container_group.container-poc-${{ github.event.inputs.env }} -auto-approve
    
    - name: Try terraform plan on TEST env
      if: ${{ github.event.inputs.env == 'test' }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform plan -var application_version=${{ github.event.inputs.version }} -target azurerm_container_group.container-poc-${{ github.event.inputs.env }}

    - name: Deployment on TEST env
      if: ${{ github.event.inputs.env == 'test' }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform apply -var application_version=${{ github.event.inputs.version }} -target azurerm_container_group.container-poc-${{ github.event.inputs.env }} -auto-approve