
name: container deployment

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Deployment environment'
        options:
          - prod
          - test
        required: true
      version:
        description: 'application version'
        required: true

jobs:
  
  deploy_on_azure_container_service:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name:
      run: echo "${{ github.event.inputs.version }}"
    
    - name:
      run: echo "${{ github.event.inputs.env }}"