
name: container deployment

on:
  workflow_dispatch:

jobs:
  
  deploy_on_azure_container_service:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Initialize Terraform
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform init

    - name: Try terraform plan
      env:
        ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform plan -var client_secret="$ARM_CLIENT_SECRET"

    - name: Deploy on azure conatianer service
      env:
        ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
      working-directory: ./containerization/infrastructure/deploy-container
      run: terraform apply -var client_secret="$ARM_CLIENT_SECRET" -auto-approve