name: Build docker image

on:
  workflow_dispatch:

jobs:

  build_docker_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to docker registry
      env: 
        registry_token: ${{ secrets.REGISTRY_TOKEN }}
      run: docker login -u sngbango -p $registry_token
    
    - name: build docker image
      run: ls

    