name: Deploy app on Azure

on:
  workflow_dispatch:

jobs:

  build_k8s_cluster:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set Azure credentials
      env:
        ARM_CLIENT_ID: ${{  secrets.ARM_CLIENT_ID  }}
        ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
        ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID  }}
        ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID  }}
      run: |
        touch az_var.txt
        echo ARM_CLIENT_ID="$ARM_CLIENT_ID" >> az_var.txt
        echo ARM_CLIENT_SECRET="$ARM_CLIENT_SECRET" >> az_var.txt
        echo ARM_TENANT_ID="$ARM_TENANT_ID" >> az_var.txt
        echo ARM_SUBSCRIPTION_ID="$ARM_SUBSCRIPTION_ID" >> az_var.txt

    - name: Initialize Terraform
      working-directory: ./containerization/infrastructure/deploy-kubernetes
      run: source az_var.txt

    - name: Try terraform plan
      working-directory: ./containerization/infrastructure/deploy-kubernetes
      run: echo "coucou"