name: Deploy app on Azure

on:
  workflow_dispatch:

jobs:

  build_k8s_cluster:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Initialize Terraform
      working-directory: ./containerization/infrastructure/deploy-kubernetes
      run: terraform init

    - name: Try terraform plan
      env:
        ARM_CLIENT_SECRET: ${{  secrets.ARM_CLIENT_SECRET  }}
      working-directory: ./containerization/infrastructure/deploy-kubernetes
      run: terraform plan -var client_secret="$ARM_CLIENT_SECRET"