name: Deploy app on Azure

on:
  workflow_dispatch:

jobs:

  build_k8s_cluster:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: 
      working-directory: ./containerization/infrastructure/deploy-kubernetes
      run: terraform init

    - name: 
      working-directory: ./containerization/infrastructure/deploy-kubernetes
      env:
        TENANT_ID: ${{  secrets.TENANT_ID  }}
        SUBSCRIPTION_ID: ${{  secrets.SUBSCRIPTION_ID  }}
      run: terraform plan -var tenant_id="$TENANT_ID" -var subsciption_id="$SUBSCRIPTION_ID"